default-action = allow

# set action to "auth" whenever the user is logged is (e.g. the authentication
# cookie is set), since otherwise (in case of action "allow")
# traefik-forward-auth doesn't send the username header value, but # at the
# same time take care not to replace the LogoutHandler for the # /_oauth/logout
# route.
rule.loggedin.action = auth
rule.loggedin.rule = HeadersRegexp("cookie", ".*_forward_auth=.*") && Path("/{path:$|[^_].*$}")

rule.login.action = auth
rule.login.rule = PathPrefix("/login")

rule.lecturers.action = auth
rule.lecturers.rule = PathPrefix("/create")

rule.api.action = auth
rule.api.rule = PathPrefix("/ltapi/{session:[0-9]+}/{stream:[0-9]+}/append") || PathPrefix("/ltapi/{session:[0-9]+}/{-:set|add}") || PathPrefix("/ltapi/{-:get_default|get_demo|start|add}")

rule.gettoken.action = auth
rule.gettoken.rule = PathPrefix("/gettoken")

rule.monitoring.action = auth
rule.monitoring.rule = PathPrefix("/monitoring")
rule.monitoring.whitelist = admin@example.com
