version: "3.3"


services:

  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.route-prefix=/monitoring"
      - "--web.external-url=https://${DOMAIN_PORT:-${DOMAIN}}/monitoring"
    #ports:
    #  - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - LTPipeline
    labels:
      - 'pipeline=${PIPELINE_NAME:-main}'
      - 'traefik.enable=true'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'
      - 'traefik.http.routers.prometheus.tls=true'
      - 'traefik.http.routers.prometheus.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.prometheus.rule=Host(`${DOMAIN}`) && PathPrefix(`/monitoring`)'
      - 'traefik.http.routers.prometheus.middlewares=traefik-forward-auth'
    restart: 'unless-stopped'
