version: "3.3"

services:
  bot:
    image: registry.isl.iar.kit.edu/bot
    build:
      dockerfile: Dockerfile
      context: dialog/bot
    command: python -u server.py --queue-server kafka --queue-port 9092 --redis-server redis
    networks:
      - LTPipeline
    environment:
      - QUEUE_SYSTEM=${QUEUE_SYSTEM:-KAFKA}
      - DEBUG=True
    restart: on-failure
    volumes:
      - archive:/logs/archive
  kitmeetingbutler:
    image: registry.isl.iar.kit.edu/kitmeetingbutler
    build:
      dockerfile: Dockerfile
      context: dialog/kitmeetingbutler
    command: python -u KITMeetingButler.py --queue-server kafka --queue-port 9092 --redis-server redis
    networks:
      - LTPipeline
    environment:
      - QUEUE_SYSTEM=${QUEUE_SYSTEM:-KAFKA}
      - DEBUG=True
      - HF_TOKEN=$hf_token
    restart: on-failure
